### ISSUE TITLE
Add support for 1.17

### ISSUE THREAD

**Issue by SvenHaarig** [NathanCollaert/AugmentedHardcore#10]
Hello,
Is it possible to update this Plugin to 1.17? Because I´ve encountered a lot of bugs while testing it to see if it would still work. This Plugin causes the server to crash when you are writing the command "/augmentedhardcore:deathbans". It also doesn´t work sometimes. Sometimes you get banned on death and sometimes not despite it being the same cause of death. But it will guarantee to work after you reload the server.

Kind regards.
Sven

**Comment by NathanCollaert** [comment]
1.17 support is now available with v3.3.2
