### ISSUE TITLE
Deaths Till Raidable

### ISSUE THREAD

**Issue by hdpow** [NathanCollaert/AugmentedHardcore#22]
Would it be possible to add DTR? if you are unfamiliar, DTR is basically a feature from hardcore factions or hcf where a player would have a DTR assigned to his group, the max of which would be the number of members in this group plus .1. every time a player died, the group would lose one DTR. if your DTR ever dropped below zero, any person would be able to build or interact with blocks in your claim. I understand that this plugin does not feature claims or groups, but would it be possible to make this happen somehow in terms of compatibility?

**Comment by NathanCollaert** [comment]
I think this is a little out of the scope of AH currently. What keeps you from running Hardcore Factions with AH together?
