### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by Decius07** [NathanCollaert/AugmentedHardcore#39]
Are you able to add something like a Life Item? Or like a Revive Item?

**Comment by NathanCollaert** [comment]
Currently this is not on the to do no, I'm sure this can be done through another plugin.

**Comment by Decius07** [comment]
No, it can not be done with other Plugins, but I also made my own version of this Plugin with a Revive and an Extra Life Item. If you want, i can send it here.

**Comment by Decius07** [comment]
Also with a Life withdraw feature.

**Comment by vpttyn** [comment]
try Executable Items. to make it
