### ISSUE TITLE
Feature Requests!

### ISSUE THREAD

**Issue by Flavourized** [NathanCollaert/AugmentedHardcore#4]
Hello, was asked to make this a github issue!

1) Adding PlaceholderAPI placeholders for the following: 
  - Ban time in seconds/minutes/hours/days
  - Ban time expire date
  - last ban date
  - total bans
  - current lives
  - current lifeparts
  - parts needed for life
  - time in sec/min/hr/day until next lifepart (if enabled)
  - time in sec/min/hr/day until next life (if enabled)
 
2) Hooking with existing Combat Tag plugins
  - I see that LDB has a basic combat tag system. It would be nice if it could hook to an existing combattag plugin (if it exists), and use that plugin to handle combat tag related things. We specifically use CombatLogX

Thank you in advance!

**Comment by NathanCollaert** [comment]
This has been added in version 3.0.0 of the plugin. Sorry for the wait.
