### ISSUE TITLE
[Suggestion] Make the aliases configurable

### ISSUE THREAD

**Issue by apatuka** [NathanCollaert/AugmentedHardcore#41]
Greetings,

I have other plugins using the /ah alias command, so if it's possible to add as feature a way to config the aliases so i can change to another command alias.

**Comment by NathanCollaert** [comment]
Hi there, you can always use the full command name `/augmentedhardcore`. If this doesn't fulfill your needs you can always make a custom alias with the build in Bukkit feature for this in the commands.yml file.
