### ISSUE TITLE
InventoryClickEvent AugmentedHardcore v3.3.7

### ISSUE THREAD

**Issue by vpttyn** [NathanCollaert/AugmentedHardcore#43]
![image](https://user-images.githubusercontent.com/93665377/219874194-c2ac4b22-c7b5-484b-bd23-05613a98028f.png)
When ever i click on menu /ms

**Comment by NathanCollaert** [comment]
Hi there, this bug has been fixed in version 3.3.8, now available on the Spigot page of the plugin.
