### ISSUE TITLE
[Feature Request] Spectator Mode after DeathBan

### ISSUE THREAD

**Issue by maxerium** [NathanCollaert/AugmentedHardcore#5]
Hey! I'm currently in the process of setting up a server for a friend of mine and we're planning to use your plugin.

To - of course - moderate the server properly without the players whining about staff not being banned after dying, would it be possible for you to add the function to get forced into spectator mode for the time being of you normally being banned? That way, staff could still moderate the server yet be _banned_.

**Comment by NathanCollaert** [comment]
Simple request, should be possible!

**Comment by maxerium** [comment]
Is there any possible sort of ETA for when this can be a thing?

I'm planning to release the server quite soonish, and I'm pumped to use this asap.

**Comment by NathanCollaert** [comment]
Hey there, I've been thinking about it and ran into a small problem with it.
I was thinking if just adding a special permission you could give your admins so they'd be put into spectator upon deathban but what do we want to happen once the "ban" runs out? Should I put them right there right now back to survival, meaning they could die from fall damage or randomly appear for other players next to them. And what if you remove the permission once someone is deathbanned into spectator, the plugin wouldn't know what to do with the player.

**Comment by maxerium** [comment]
> And what if you remove the permission once someone is deathbanned into spectator, the plugin wouldn't know what to do with the player.
That will never happen, since the permission is only going to be given to trusted people that have been known for a long time.

> but what do we want to happen once the "ban" runs out?
Perhaps, add a timer (?) that gives them a message like 1 or 5 minutes before their deathban ends so they know to either go to a safe location or just go to spawn.

**Comment by NathanCollaert** [comment]
This has been added in version 3.0.0 of the plugin. Sorry for the wait.
