### ISSUE TITLE
/revive will unban anyone for anything

### ISSUE THREAD

**Issue by TwoPointInfinity** [NathanCollaert/AugmentedHardcore#7]

**Comment by TwoPointInfinity** [comment]
Thats just it. Anyone who is banned with "/ban [player] [reason]" can be unbanned by another player with "/revive" allowing alt accounts to unban their main or friends to unban their griefer / cheater. If there could be a way that /revive only unbans players who were banned by litedeathbans that'd be amazing.

**Comment by TwoPointInfinity** [comment]
until this is fixed or there is a work around /revive is unusable in my opinion.

**Comment by NathanCollaert** [comment]
Hey there, I've answered your question on the Spigot page of LDB.

**Comment by NathanCollaert** [comment]
This has been added in version 3.0.0 of the plugin. Sorry for the wait.
