### ISSUE TITLE
no command to unban players only banned by litedeathban

### ISSUE THREAD

**Issue by TwoPointInfinity** [NathanCollaert/AugmentedHardcore#8]
there is no way to unban players from the console that have been banned specifically by litedeathbans. You can add a life but that does not unban them, you would then have to send the unban command. But this would allow the unbanning of anyone who has been banned. 
I have run into this issue where im allowing players to either wait out their ban time OR donate to the server to come back immediately. But in doing this they can donate to the server and input their username and it would send the unban command to the server. This would unban them even if one of my admins banned them.

**Comment by NathanCollaert** [comment]
This has been added in version 3.0.0 of the plugin. Sorry for the wait.
